# Generated by Django 3.0.4 on 2020-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctoronlineapplication', '0002_auto_20200426_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pricing',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='speciality',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
