# Generated by Django 3.0.4 on 2020-04-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctoronlineapplication', '0003_auto_20200428_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_created',
            field=models.DateTimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateofbirth',
            field=models.DateField(max_length=120),
        ),
    ]
