# Generated by Django 3.0.4 on 2020-04-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctoronlineapplication', '0004_auto_20200428_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer not to say', 'Prefer Not To Say')], default='Select a gender', max_length=256),
        ),
    ]
